### ISSUE TITLE
Devlings are too weak

### ISSUE THREAD

**Issue by ProditorMagnus** [sevu/EoM#1]
I have asked IPS for help, there should soon be changes available.

**Comment by sevu** [comment]
ok, great =)

**Comment by sevu** [comment]
What traits in ageless are similar to loyal, or decreasing upkeep? Maybe there is already a fitting name.
And did you have sth. specific in mind for the Flappers line? I think we talked once about them, long ago?

**Comment by ProditorMagnus** [comment]
Nothing as trait, I handle upkeep only with dummy ability https://github.com/ProditorMagnus/Ageless-for-1-11/blob/master/units/EoMa_units/Destroyers/Piranha_Monstruosa.cfg#L44.

I would increase damage and hp for flappers.

**Comment by sevu** [comment]
This is a good idea, this leaves you still with plqce for two traits. I thought it was a dummy trait.

**Comment by sevu** [comment]
I will merge this later into ageless. I'm hallways done with it, but have no time time anymore right now.

**Comment by sevu** [comment]
Could you include this event:
https://github.com/sevu/EoM/blob/master/EOM_eras.cfg#L98
I'm not sure where to put it best

**Comment by ProditorMagnus** [comment]
I will, event definition to data/era_events, and including it from ageless and ageless heroes [era].

**Comment by ProditorMagnus** [comment]
Though, if you think it should be active for rpg too, then include it from eras/era_events/_main.cfg instead?

**Comment by sevu** [comment]
Didn't consider RPG so far, but it's a good idea.
The Overgrown needs to be in the type filtering then too.

**Comment by ProditorMagnus** [comment]
Done.
